name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          pip install -r notebooks/requirements.txt

      - name: Build documentation
        run: |
          make -C docs html
          jb build --path-output build/jupyter-book notebooks
          mkdir -p site/docs site/notebooks
          mv build/sphinx/html/* site/docs
          mv build/jupyter-book/html/* site/notebooks

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site